- name: Install External Secrets Operator helm chart
  kubernetes.core.helm:
    release_name: external-secrets
    chart_ref: external-secrets
    chart_repo_url: https://charts.external-secrets.io
    release_namespace: external-secrets
    create_namespace: yes
    wait: yes
  become_user: "{{admin_user}}"
