---
- name: Install pip packages
  pip:
    name:
      - kubernetes

- name: Install microk8s snap
  snap:
    #classic: yes
    name: microk8s
    #channel: 1.24/stable

- name: Install helm snap package
  snap:
    classic: yes
    name: helm

- name: Add admin user to microk8s group
  user:
    name: "{{admin_user}}"
    groups: microk8s
    append: yes

- name: Enable microk8s services
  command: "microk8s enable {{item}}"
  with_items: "{{microk8s_services}}"

- import_tasks: k9s.yml
- import_tasks: kubectl.yml
- import_tasks: vcluster.yml

- name: Make iptables changes persistent
  apt:
    name: "{{packages}}"
    state: present
    update_cache: yes
  vars:
    packages:
    - iptables-persistent

- name: Make sure pods have access to internet
  iptables:
    chain: FORWARD
    policy: ACCEPT

- name: Install Helm Diff
  kubernetes.core.helm_plugin:
    state: present
    plugin_path: https://github.com/databus23/helm-diff
  become_user: "{{admin_user}}"

