---
- name: Install pip packages
  pip:
    name:
      - kubernetes

- name: Install microk8s snap
  snap:
    classic: yes
    name: microk8s

- name: Add admin user to microk8s group
  user:
    name: "{{admin_user}}"
    groups: microk8s
    append: yes

- name: Enable microk8s services
  command: "microk8s enable {{item}}"
  with_items: "{{microk8s_services}}"

- name: Make iptables changes persistent
  apt:
    name: "{{packages}}"
    state: present
    update_cache: yes
  vars:
    packages:
    - iptables-persistent

- name: Make sure pods have access to internet
  iptables:
    chain: FORWARD
    policy: ACCEPT

- import_tasks: k9s.yml
- import_tasks: kubectl.yml
- import_tasks: vcluster.yml
- import_tasks: helm.yml
