- name: Transfer reloaded config values file
  template:
    src: reloader-values.yml
    dest: /tmp/reloader-values.yml

- name: Install reloader helm chart
  kubernetes.core.helm:
    release_name: reloader
    chart_ref: reloader
    chart_repo_url: https://stakater.github.io/stakater-charts
    release_namespace: reloader
    create_namespace: yes
    wait: yes
    values_files:
      - /tmp/reloader-values.yml
  become_user: "{{admin_user}}"
