---
- name: Install vcluster
  get_url:
    url: https://github.com/loft-sh/vcluster/releases/latest/download/vcluster-linux-amd64
    dest: /usr/local/bin/vcluster
    owner: root
    group: root
    mode: 0755
    validate_certs: no

- name: Create vcluster zsh alias
  lineinfile:
    path: "/home/{{admin_user}}/.zshrc"
    line: alias vc='vcluster'
    create: yes
