# Ref: https://github.com/stakater/Reloader/blob/master/deployments/kubernetes/chart/reloader/values.yaml
image:
  tag: v1.4.1
reloader:
  autoReloadAll: true
  isArgoRollouts: true
  namespaceSelector: "kubernetes.io/metadata.name=production"
